const listIsotope = [
  {
    id: 1,
    name: 'App 1',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-app',
    link: '',
    img: 'images/portfolio/app-1.jpg',
  },
  {
    id: 2,
    name: 'Product 1',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-product',
    link: '',
    img: 'images/portfolio/product-1.jpg',
  },
  {
    id: 3,
    name: 'Branding 1',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-branding',
    link: '',
    img: 'images/portfolio/branding-1.jpg',
  },
  {
    id: 4,
    name: 'Books 1',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-books',
    link: '',
    img: 'images/portfolio/books-1.jpg',
  },
  {
    id: 5,
    name: 'App 2',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-app',
    link: '',
    img: 'images/portfolio/app-2.jpg',
  },
  {
    id: 6,
    name: 'Product 2',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-product',
    link: '',
    img: 'images/portfolio/product-2.jpg',
  },
  {
    id: 7,
    name: 'Branding 2',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-branding',
    link: '',
    img: 'images/portfolio/branding-2.jpg',
  },
  {
    id: 8,
    name: 'Books 2',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-books',
    link: '',
    img: 'images/portfolio/books-2.jpg',
  },
  {
    id: 9,
    name: 'App 3',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-app',
    link: '',
    img: 'images/portfolio/app-3.jpg',
  },
  {
    id: 10,
    name: 'Product 3',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-product',
    link: '',
    img: 'images/portfolio/product-3.jpg',
  },
  {
    id: 11,
    name: 'Branding 3',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-branding',
    link: '',
    img: 'images/portfolio/branding-3.jpg',
  },
  {
    id: 12,
    name: 'Books 3',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-books',
    link: '',
    img: 'images/portfolio/books-3.jpg',
  },
];

export default listIsotope;
