const listIsotope = [
  {
    id: 1,
    name: 'Wmz',
    description: 'Velikoluksky Mechanical Factory',
    filter: 'filter-websites',
    link: 'https://wmz.ru/',
    img: 'images/portfolio/wmz.webp',
  },
  {
    id: 2,
    name: 'Kontakor',
    description: 'Contact correction center',
    filter: 'filter-websites',
    link: 'https://kontakor.ru/',
    img: 'images/portfolio/kontakor.webp',
  },
  {
    id: 3,
    name: 'Branding 1',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-mobile',
    link: '',
    img: 'images/portfolio/branding-1.jpg',
  },
  {
    id: 4,
    name: 'Books 1',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-startups',
    link: '',
    img: 'images/portfolio/books-1.jpg',
  },
  {
    id: 5,
    name: 'App 2',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-websites filter-webapps',
    link: '',
    img: 'images/portfolio/app-2.jpg',
  },
  {
    id: 6,
    name: 'Product 2',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-product',
    link: '',
    img: 'images/portfolio/product-2.jpg',
  },
  {
    id: 7,
    name: 'Branding 2',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-mobile filter-startups',
    link: '',
    img: 'images/portfolio/branding-2.jpg',
  },
  {
    id: 8,
    name: 'Books 2',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-websites filter-webapps',
    link: '',
    img: 'images/portfolio/books-2.jpg',
  },
  {
    id: 9,
    name: 'App 3',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-mobile',
    link: '',
    img: 'images/portfolio/app-3.jpg',
  },
  {
    id: 10,
    name: 'Product 3',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-startups',
    link: '',
    img: 'images/portfolio/product-3.jpg',
  },
  {
    id: 11,
    name: 'Branding 3',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-websites',
    link: '',
    img: 'images/portfolio/branding-3.jpg',
  },
  {
    id: 12,
    name: 'Books 3',
    description: 'Lorem ipsum, dolor sit amet consectetur',
    filter: 'filter-webapps',
    link: '',
    img: 'images/portfolio/books-3.jpg',
  },
];

export default listIsotope;
